Autopraonica.Web/Autopraonica.Web/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Autopraonica.Model;
using System.Data.Entity;

namespace Autopraonica.Web.Controllers
{
    public class ReservationController : BaseController
    {
        //Reservation
        public ActionResult Index()
        {
            var model = dbContext.Reservations.ToList();
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var model = dbContext.Reservations.First(p => p.ID == id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var model = dbContext.Reservations.First(p => p.ID == id);
            FillDropdowns();
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Reservation model)
        {
            if (ModelState.IsValid)
            {
                
                dbContext.Reservations.Attach(model);

                var entry = dbContext.Entry(model);
                entry.State = EntityState.Modified;

                entry.Property(p => p.Length).IsModified = true;
                entry.Property(p => p.VehicleType).IsModified = true;
                entry.Property(p => p.CompanyID).IsModified = true;
                entry.Property(p => p.ClientID).IsModified = true;

                dbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            FillDropdowns();
            return View(model);
        }

        public ActionResult Create()
        {
            FillDropdowns();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Reservation model)
        {
            if(ModelState.IsValid)
            {
                dbContext.Reservations.Add(model);
                dbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            FillDropdowns();
            return View();
        }

        public ActionResult Delete(int id)
        {
            var model = dbContext.Reservations.First(p => p.ID == id);

            dbContext.Reservations.Remove(model);
            dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        //Client
        public ActionResult ClientIndex()
        {
            var model = dbContext.Clients.ToList();
            return View(model);
        }

        public ActionResult ClientDetails(int id)
        {
            var model = dbContext.Clients.First(p => p.ID == id);
            return View(model);
        }

        public ActionResult ClientDelete(int id)
        {
            var lista = dbContext.Reservations.Where(p => p.ClientID == id).ToList();
            foreach (var reservation in lista)
            {
                dbContext.Reservations.Attach(reservation);

                var entry = dbContext.Entry(reservation);
                entry.State = EntityState.Modified;

                entry.Property(p => p.ClientID).CurrentValue = 1;
                entry.Property(p => p.ClientID).IsModified = true;

                dbContext.SaveChanges();
            }

            var model = dbContext.Clients.First(p => p.ID == id);
            dbContext.Clients.Remove(model);
            dbContext.SaveChanges();

            return RedirectToAction("ClientIndex");
        }

        public ActionResult ClientCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ClientCreate(Client model)
        {
            if (ModelState.IsValid)
            {
                model.DateCreated = DateTime.Now;
                dbContext.Clients.Add(model);
                dbContext.SaveChanges();

                return RedirectToAction("ClientIndex");
            }
            return View(model);
        }

        public ActionResult ClientEdit(int id)
        {
            var model = dbContext.Clients.First(p => p.ID == id);
            return View(model);
        }

        [HttpPost]
        public ActionResult ClientEdit(Client model)
        {
            if (ModelState.IsValid)
            {
                dbContext.Clients.Attach(model);

                var entry = dbContext.Entry(model);
                entry.State = EntityState.Modified;

                entry.Property(p => p.Name).IsModified = true;
                entry.Property(p => p.Surname).IsModified = true;
                entry.Property(p => p.Email).IsModified = true;


                dbContext.SaveChanges();
                return RedirectToAction("ClientIndex");
            }
            return View(model);
        }

        private void FillDropdowns()
        {
            var possibleCompanies = dbContext.Companies.ToList();

            var selectItems = new List<SelectListItem>();

            var listItem = new SelectListItem();
            listItem.Text = " grad ";
            listItem.Value = "";
            selectItems.Add(listItem);

            foreach (var company in possibleCompanies)
            {
                listItem = new SelectListItem();
                listItem.Text = company.Name;
                listItem.Value = company.ID.ToString();
                listItem.Selected = false;
                selectItems.Add(listItem);
            }
            ViewBag.PossibleCompanies = selectItems;


            var possibleClients = dbContext.Clients.ToList();

            var selectItems2 = new List<SelectListItem>();

            var listItem2 = new SelectListItem();
            listItem2.Text = " Klijenti ";
            listItem2.Value = "";
            selectItems2.Add(listItem2);

            foreach (var client in possibleClients)
            {
                listItem2 = new SelectListItem();
                listItem2.Text = client.Name + " " + client.Surname;
                listItem2.Value = client.ID.ToString();
                listItem2.Selected = false;
                selectItems2.Add(listItem2);
            }
            ViewBag.PossibleClients = selectItems2;
        }
    }
}

Autopraonica.Web/Autopraonica.Web/Views/Reservation/ClientCreate.cshtml

@{
    ViewBag.Title = "ClientCreate";
}

<h2>Dodavanje klijenta</h2>

@using (Html.BeginForm())
{
    <text>
        @Html.Partial("_ClientCreateOrEdit")
    </text>

}
<p class="btn btn-default">
    @Html.ActionLink("Povratak", "ClientIndex")
</p>


Autopraonica.Web/Autopraonica.Web/Views/Reservation/ClientDetails.cshtml
@model Autopraonica.Model.Client
<div class="form-horizontal">
    <br />
    <div class="form-group">
        Ime klijenta:
        @Html.ValueFor(model => model.Name)
    </div>
    <div class="form-group">
        Prezime klijenta:
        @Html.ValueFor(model => model.Surname)
    </div>
    <div class="form-group">
        Broj rezervacija:
        @Html.ValueFor(model => model.Reservations.Count)
    </div>
    <div class="form-group">
        E-Mail:
        @Html.ValueFor(model => model.Email)
    </div>

    @Html.HiddenFor(model => model.ID)

    <p class="btn btn-default">
        @Html.ActionLink("Povratak", "Index", "Reservation")
    </p>
</div>

Autopraonica.Web/Autopraonica.Web/Views/Reservation/ClientEdit.cshtml
@model Autopraonica.Model.Client
@{
    ViewBag.Title = "ClientEdit";
}

<h2>Uređivanje klijenta</h2>

@using (Html.BeginForm())
{
    <text>
        @Html.Partial("_ClientCreateOrEdit", Model)
    </text>

}
<p class="btn btn-default">
    @Html.ActionLink("Povratak", "ClientIndex")
</p>


Autopraonica.Web/Autopraonica.Web/Views/Reservation/ClientIndex.cshtml
@model List<Autopraonica.Model.Client>
@{
    ViewBag.Title = "ClientIndex";
}
<h2>Pregled Klijenata</h2>
<br />

<p class="btn btn-default">
    @Html.ActionLink("Dodaj Klijenta", "ClientCreate")
</p>

<br /><br />
@Html.Partial("_ClientIndexTable", Model)
<br />
<p class="btn btn-default">
    @Html.ActionLink("Povratak", "Index", "Reservation")
</p>

Autopraonica.Web/Autopraonica.Web/Views/Reservation/Create.cshtml
@model Autopraonica.Model.Reservation

@{
    ViewBag.Title = "Nova rezervacija";
}
<h2>Dodavanje nove rezervacije</h2>
@using (Html.BeginForm())
{
    <text>
        @Html.Partial("_CreateOrEdit")
    </text>

}
<br />
<p class="btn btn-default">
    @Html.ActionLink("Povratak", "Index")
</p>

Autopraonica.Web/Autopraonica.Web/Views/Reservation/Details.cshtml
@model Autopraonica.Model.Reservation
<div class="form-horizontal">
    <br />
    <div class="form-group">
        Poslovnica:
        @Html.ValueFor(model => model.Company.Name)
    </div>
    <div class="form-group">
        Adresa:
        @Html.ValueFor(model => model.Company.Address)
    </div>
    <div class="form-group">
        Tip vozila:
        @Html.ValueFor(model => model.VehicleType)
    </div>
    <div class="form-group">
        Trajanje:
        @Html.ValueFor(model => model.Length)
    </div>
    <div class="form-group">
        Ime klijenta:
        @Html.ValueFor(model => model.Client.Name)
    </div>
    <div class="form-group">
        Prezime klijenta:
        @Html.ValueFor(model => model.Client.Surname)
    </div>

    @Html.HiddenFor(model => model.ID)

    <p class="btn btn-default">
        @Html.ActionLink("Povratak", "Index", "Reservation")
    </p>
</div>

Autopraonica.Web/Autopraonica.Web/Views/Reservation/Edit.cshtml
@model Autopraonica.Model.Reservation
@{
    ViewBag.Title = "Uređivanje poslovnice";
}

<h2>Uređivanje poslovnice</h2>

@using (Html.BeginForm())
{

    <text>
        @Html.Partial("_CreateOrEdit")
        @Html.HiddenFor(p => p.ID)
    </text>
}

<div>
    <p class="btn btn-default">
        @Html.ActionLink("Povratak", "Index")
    </p>
</div>

Autopraonica.Web/Autopraonica.Web/Views/Reservation/Index.cshtml
@model List<Autopraonica.Model.Reservation>
@{
    ViewBag.Title = "Index";
}
<h2>Pregled Rezervacija</h2>
<br />

<p class="btn btn-default">
    @Html.ActionLink("Dodaj Rezervaciju", "Create")
</p>

<p class="btn btn-default">
    @Html.ActionLink("Pregled klijenata", "ClientIndex")
</p>
<br /><br />
    @Html.Partial("_IndexTable", Model)
<br />
<p class="btn btn-default">
    @Html.ActionLink("Povratak", "Index", "Home")
</p>

Autopraonica.Web/Autopraonica.Web/Views/Reservation/_ClientCreateOrEdit.cshtml
@model Autopraonica.Model.Client

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>

Autopraonica.Web/Autopraonica.Web/Views/Reservation/_ClientIndexTable.cshtml
@model List<Autopraonica.Model.Client>

<table id="tbl-companies" class="table table-condensed table-hover">
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezmie</th>
            <th>eMail</th>
            <th>Broj rezervacija</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var client in Model)
        {
            <tr>
                <td>@client.Name</td>
                <td>@client.Surname</td>
                <td>@client.Email</td>
                <td>@client.Reservations.Count</td>
                <td>@Html.ActionLink("Uredi", "ClientEdit", new { id = client.ID })</td>
                <td>@Html.ActionLink("Obriši", "ClientDelete", new { id = client.ID })</td>
            </tr>
        }

    </tbody>
</table>

Autopraonica.Web/Autopraonica.Web/Views/Reservation/_CreateOrEdit.cshtml
@model Autopraonica.Model.Reservation

<div class="form-horizontal">

    <div class="form-group">
        @Html.LabelFor(model => model.VehicleType, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.VehicleType, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Length, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Length, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClientID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.ClientID, (IEnumerable<SelectListItem>)ViewBag.PossibleClients, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CompanyID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CompanyID, (IEnumerable<SelectListItem>)ViewBag.PossibleCompanies, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>



Autopraonica.Web/Autopraonica.Web/Views/Reservation/_IndexTable.cshtml
@model List<Autopraonica.Model.Reservation>

<table id="tbl-companies" class="table table-condensed table-hover">
    <thead>
        <tr>
            <th>Poslovnica</th>
            <th>Tip Vozila</th>
            <th>Trajanje</th>
            <th>Klijent</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var reservation in Model)
        {
            <tr>
                <td>@reservation.Company.Name</td>
                <td>@reservation.VehicleType</td>
                <td>@reservation.Length sati</td>
                <td>@reservation.Client.Surname</td>
                <td>@Html.ActionLink("Klijent", "ClientDetails", new { id = reservation.ClientID })</td>
                <td>@Html.ActionLink("Detalji", "Details", new { id = reservation.ID })</td>
                <td>@Html.ActionLink("Uredi", "Edit", new { id = reservation.ID })</td>
                <td>@Html.ActionLink("Obriši", "Delete", new { id = reservation.ID })</td>
            </tr>
        }

    </tbody>
</table>